title: Web Apps Index
baseurl: ""
url: ""
exclude:
  - .github/
  - README.md

# Process all HTML files, even without front matter
include:
  - "**/*.html"
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default" 