title: Web Apps Index
baseurl: ""
url: ""
exclude:
  - .github/
  - README.md

# Process all files recursively
include:
  - "**/*"
  - "**/.*"

# Set default layout for all files
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Keep the source directory clean
keep_files: [".git"]

# Enable recursive directory reading
safe: false 